### ISSUE TITLE
资源管理-主机管理-详情“机架”内容是“主机名称”

### ISSUE THREAD

**Issue by xiaobao623** [upmio/DBScale-deploy#3]
主机管理-界面上的机位显示的是“注册”里添加的“机位”
![image](https://user-images.githubusercontent.com/11609541/40529719-b63cb3aa-6028-11e8-91bb-dbad63d13d52.png)

但是详情里显示的“机架”内容是“主机名名称”。
![image](https://user-images.githubusercontent.com/11609541/40529743-c734b068-6028-11e8-8ad4-c9ec464dc331.png)

**Comment by linleybao** [comment]
fixed
https://github.com/upmio/upm/commit/f9a2904abe432309dbd8e6eddd7b285e1213dc54
